<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DomainEvents\" />
    <Folder Include="BusinessRules\" />
    <Folder Include="Interfaces\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LMS.Common\LMS.Common.csproj" />
  </ItemGroup>

</Project>
